---
- name: Sign Certificate
  hosts: dc01
  become: true
  tasks:
    - name: Generate Private Key
      community.crypto.openssl_privatekey_pipe:
        type: RSA
        size: 4096
      register: private
    - name: Store key
      ansible.builtin.copy:
        owner: root
        group: network
        mode: 'u+rw,g+rw,o+r'
        dest: >-
          {{ np.key }}
        content: >-
          {{ private.privatekey }}
      delegate_to: >-
        {{ np.cn }}
    - name: Generate CSR
      community.crypto.openssl_csr_pipe:
        privatekey_path: >-
          {{ np.key }}
        common_name: >-
          {{ np.cn }}
        subject_alt_name: >-
          {{ np.san }}
      register: csr
    - name: Ensure CSR directory
      ansible.builtin.file:
        dest: "/etc/ssl/csr"
        state: directory
        owner: root
        group: network
        mode: "u+rwx,g+rwx,o+rx"
      delegate_to: np
    - name: Store CSR
      ansible.builtin.copy:
        owner: root
        group: network
        mode: 'u+rw,g+rw,o+r'
        dest: >-
          {{ np.csr }}
        content: >-
          {{ csr.csr }}
      delegate_to: np
    - name: Sign Certificate
      community.crypto.x509_certificate_pipe:
        privatekey_path: >-
          {{ np.key }}
        csr_path: >-
          {{ np.csr }}
        ownca_path: >-
          {{ int_ca.paths.crt }}
        ownca_privatekey_path: >-
          {{ int_ca.paths.key }}
        provider: ownca
      register: certi
    - name: Store certificate
      ansible.builtin.copy:
        owner: root
        group: network
        mode: 'u+rw,g+rw,o+r'
        dest: >-
          {{ np.crt }}
        content: >-
          {{ certi.certificate }}
      delegate_to: np
