###
# ```{rubric} MarkdownLint Configuration
# ```
# ---
# An example .markdownlint-cli2.yaml file
#
# Disable some built-in rules
config:
  no-multiple-blanks: true
  no-trailing-spaces: true

# Include a custom rule package
# customRules:
#   - markdownlint-rule-titlecase

# Fix any fixable errors
fix: true
###
# Define a custom front matter pattern
# frontMatter: "<head>[^]*<\/head>"
#
# Ignore files referenced by .gitignore (only valid at root)
gitignore: true
###
# Define glob expressions to use (only valid at root)
globs:
  - "#.venv"
###
# Define glob expressions to ignore
ignores:
  - "ignore*.md"
###
# Use a plugin to recognize math
# markdownItPlugins:
#   -
#     - "@iktakahiro/markdown-it-katex"
#
# Additional paths to resolve module locations from
modulePaths:
  - "./modules"
###
# Disable banner message on stdout (only valid at root)
noBanner: false
###
# Disable inline config comments
noInlineConfig: false
###
# Disable progress on stdout (only valid at root)
noProgress: false
###
# Use a specific formatter (only valid at root)
outputFormatters:
  - - markdownlint-cli2-formatter-junit
###
# Show found files on stdout (only valid at root)
showFound: true
