###
# ```{rubric} The main site deployment
# ```
# ---
# This playbook defines the primary site deployment code for this repository.
#
# ```{literalinclude} /site.yml
# :language: yaml
# ```
- name: Reset Kubernetes Control Planes
  hosts: ccp
  become: true
  roles:
    - role: reset
      tags:
        - reset
- name: Initialize the first control plane
  hosts: ccp
  become: true
  roles:
    - role: kv
      tags:
        - kv
    - role: init
      tags:
        - init
- name: Join the secondary and tertiary control planes
  hosts: kcp_join
  become: true
  roles:
    - role: join
      tags:
        - join
# - name: Deploy Calico CNI
#   hosts: local
#   roles:
#     - role: calico
#       tags:
#         - calico
