###
# ```{rubric} The main site deployment
# ```
# ---
# This playbook defines the primary site deployment code for this repository.
#
# ```{literalinclude} /site.yml
# :language: yaml
# ```
- name: Reset Kubernetes Control Planes
  hosts: kcp
  become: true
  roles:
    - role: reset
      tags:
        - reset
- name: Initialize the first control plane
  hosts: thw00a,cms00a
  become: true
  roles:
    - role: init
      tags:
        - init
      vars:
        init_advertise_address: "{{  kcp_advertise_address }}"
        init_cert_sans: "{{  kcp_certs_sans }}"
        init_cluster_name: "{{  kcp_cluster_name }}"
        init_control_plane_endpoint: "{{  kcp_control_plane_endpoint }}"
        init_kube_version: "{{  kcp_kube_version }}"
        init_kcp_nonroot: "{{ kcp_nonroot }}"
- name: Join the secondary and tertiary control planes
  hosts: thw00b,cms00b
  become: true
  roles:
    - role: join
      tags:
        - join
# - name: Deploy Calico CNI
#   hosts: local
#   roles:
#     - role: calico
#       tags:
#         - calico
