apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: {{ token_out.stdout }}
  ttl: 24h0m0s
  usages:
    - signing
    - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{ ansible_host }}
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: {{ inventory_hostname }}
  taints: null
---
apiServer:
  certSANs: {{ kcp_certsans }}
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: breeze-blocks
controllerManager: {}
controlPlaneEndpoint: {{ kcp_aa }}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: 1.30.0
networking:
  dnsDomain: cluster.local
  podSubnet: 10.128.0.0/12
  serviceSubnet: 10.96.0.0/12
scheduler: {}
