###
# ```{rubric} Ansible Lint Jobs
# ```
# ---
# This action lints Ansible code for quality.
#
# ```{literalinclude} .github/workflows/ansible-lint.yml
# :language: yaml
# :caption: .github/workflows/ansible-lint.yml
# ```
name: Ansible Lint
on:
  pull_request:
    branches: ["main", "stable", "release/v*"]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    ###
    # Naming the build is important to use it as a status check
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.14
      - name: Add virtualenv
        run: python3.14 -m venv .pipenv
      - name: Install pipenv
        run: .pipenv/bin/pip3.14 install -v pipenv
      - name: Install requirements from pipenv
        run: .pipenv/bin/pipenv install --dev
      - name: Install community.crypto
        run: .pipenv/bin/pipenv run -v ansible-galaxy collection install community.crypto
      - name: Install community.general
        run: .pipenv/bin/pipenv run -v ansible-galaxy collection install community.general
      - name: Make ansible directory
        run: sudo mkdir -pv /etc/ansible
      - name: Update ansible dir ownership
        run: SUSER=$(whoami) sudo chown ${SUSER} /etc/ansible
      - name: Add a vault file
        run: echo "Pass" > /etc/ansible/vault
      - name: Run ansible-lint
        ###
        # or version tag instead of 'main'
        uses: ansible/ansible-lint@main
